export const BOOKS_OT = [
  "Genesis",
  "Exodus",
  "Leviticus",
  "Numbers",
  "Deuteronomy",
  "Joshua",
  "Judges",
  "Ruth",
  "1 Samuel",
  "2 Samuel",
  "1 Kings",
  "2 Kings",
  "1 Chronicles",
  "2 Chronicles",
  "Ezra",
  "Nehemiah",
  "Esther",
  "Job",
  "Psalms",
  "Proverbs",
  "Ecclesiastes",
  "Song of Solomon",
  "Isaiah",
  "Jeremiah",
  "Lamentations",
  "Ezekiel",
  "Daniel",
  "Hosea",
  "Joel",
  "Amos",
  "Obadiah",
  "Jonah",
  "Micah",
  "Nahum",
  "Habakkuk",
  "Zephaniah",
  "Haggai",
  "Zechariah",
  "Malachi",
];

export const BOOKS_NT = [
  "Matthew",
  "Mark",
  "Luke",
  "John",
  "Acts",
  "Romans",
  "1 Corinthians",
  "2 Corinthians",
  "Galatians",
  "Ephesians",
  "Philippians",
  "Colossians",
  "1 Thessalonians",
  "2 Thessalonians",
  "1 Timothy",
  "2 Timothy",
  "Titus",
  "Philemon",
  "Hebrews",
  "James",
  "1 Peter",
  "2 Peter",
  "1 John",
  "2 John",
  "3 John",
  "Jude",
  "Revelation",
];

// Full canonical order: Old Testament then New Testament
export const BOOKS = [...BOOKS_OT, ...BOOKS_NT];

export const CHAPTERS_PER_BOOK = {
  // OT
  Genesis: 50,
  Exodus: 40,
  Leviticus: 27,
  Numbers: 36,
  Deuteronomy: 34,
  Joshua: 24,
  Judges: 21,
  Ruth: 4,
  "1 Samuel": 31,
  "2 Samuel": 24,
  "1 Kings": 22,
  "2 Kings": 25,
  "1 Chronicles": 29,
  "2 Chronicles": 36,
  Ezra: 10,
  Nehemiah: 13,
  Esther: 10,
  Job: 42,
  Psalms: 150,
  Proverbs: 31,
  Ecclesiastes: 12,
  "Song of Solomon": 8,
  Isaiah: 66,
  Jeremiah: 52,
  Lamentations: 5,
  Ezekiel: 48,
  Daniel: 12,
  Hosea: 14,
  Joel: 3,
  Amos: 9,
  Obadiah: 1,
  Jonah: 4,
  Micah: 7,
  Nahum: 3,
  Habakkuk: 3,
  Zephaniah: 3,
  Haggai: 2,
  Zechariah: 14,
  Malachi: 4,
  // NT
  Matthew: 28,
  Mark: 16,
  Luke: 24,
  John: 21,
  Acts: 28,
  Romans: 16,
  "1 Corinthians": 16,
  "2 Corinthians": 13,
  Galatians: 6,
  Ephesians: 6,
  Philippians: 4,
  Colossians: 4,
  "1 Thessalonians": 5,
  "2 Thessalonians": 3,
  "1 Timothy": 6,
  "2 Timothy": 4,
  Titus: 3,
  Philemon: 1,
  Hebrews: 13,
  James: 5,
  "1 Peter": 5,
  "2 Peter": 3,
  "1 John": 5,
  "2 John": 1,
  "3 John": 1,
  Jude: 1,
  Revelation: 22,
};

export const VERSIONS = ["WEB", "KJV", "ASV"];

export const MODES = {
  day: {
    name: "Day",
    background: "#FFF9F0",
    text: "#2C2C2C",
    verseNumber: "#6B6B6B",
    card: "#FFFFFF",
    border: "#E8E2D6",
    accent: "#4A90E2",
    subtle: "#8B8B8B",
    highlightBg: "#F5D76E33",
  },
  night: {
    name: "Night",
    background: "#121212",
    text: "rgba(255,255,255,0.92)",
    verseNumber: "rgba(255,255,255,0.6)",
    card: "#1E1E1E",
    border: "#2A2A2A",
    accent: "#4A90E2",
    subtle: "rgba(255,255,255,0.6)",
    highlightBg: "rgba(255,215,0,0.18)",
  },
  sepia: {
    name: "Sepia",
    background: "#F4ECD8",
    text: "#3E3A2B",
    verseNumber: "#7A6F5F",
    card: "#F7F1E2",
    border: "#E5DCC7",
    accent: "#9B8FD8",
    subtle: "#8A7F6E",
    highlightBg: "rgba(240, 200, 120, 0.25)",
  },
};

export const PREF_KEYS = {
  mode: "dw_reading_mode",
  size: "dw_text_size",
  last: "dw_last_location",
  version: "dw_version",
  // ADD: Daily goal preferences
  goalType: "dw_goal_type", // 'verses' | 'minutes'
  goalTarget: "dw_goal_target", // number
};

export const HIGHLIGHT_COLORS = {
  yellow: "#FFF2A8",
  green: "#CBECCB",
  blue: "#CFE3FF",
};
